baseURL = 'https://corkbits.com/'
languageCode = 'en-us'
title = 'CorkBits'
theme = "poison"
pluralizelisttitles = false

[params]
  brand = "CorkBits"

  email_url = "mailto://corey.r.mcdaniel@live.com"
  github_url = "https://github.com/Corkle"
  linkedin_url = "https://www.linkedin.com/in/corey-mcdaniel/"

  front_page_content = ["journal"]

  # Menu dict keys:
  # Name:         The name to display on the menu.
  # URL:          The directory relative to the content directory.
  # HasChildren:  If the directory's files should be listed.  Default is true.
  # Limit:        If the files should be listed, how many should be shown.
  menu = [
      {Name = "Blog", URL = "/journal/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]
