baseURL = 'https://corkbits.com/'


languageCode = 'en-us'
title = 'CorkBits'
theme = "poison"
pluralizelisttitles = false

[params]
  brand = "CorkBits"
  brand_image = "/images/headshot.jpg"
  description = "I'm Corey McDaniel, a software engineer who loves solving problems and building awesome things. Welcome to my site where I share my thoughts and what I'm working on."

  email_url = "mailto:corey@corkbits.com"
  github_url = "https://github.com/Corkle"
  linkedin_url = "https://www.linkedin.com/in/corey-mcdaniel/"

  front_page_content = ["journal"]

  # Menu dict keys:
  # Name:         The name to display on the menu.
  # URL:          The directory relative to the content directory.
  # HasChildren:  If the directory's files should be listed.  Default is true.
  # Limit:        If the files should be listed, how many should be shown.
  menu = [
      {Name = "Projects", URL = "/projects/", HasChildren = true, Limit = 5},
      {Name = "Dev Journal", URL = "/journal/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]
